name: Moonscript Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: leafo/gh-actions-luarocks@v4
    - name: compile moonscript
      run: |
        luarocks install moonscript
        moonc mtlibrary.moon
