name: Moonscript Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: 5.1
    - uses: leafo/gh-actions-luarocks@v4
    - name: install moonscript
      run: |
        luarocks install moonscript
    - name: compile mtlibrary
      run: |
        moonc mtlib/*.moon
        moonc mtlibrary.moon
